name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build the Docker image
        run: docker build -t astro-website .

      # Step 4: Run the Docker container to generate static files
      - name: Generate static files with Docker
        run: |
          docker run --rm -v ${{ github.workspace }}/dist:/app/dist astro-website astro build
        # The `-v` option mounts the `dist` directory inside the container to retrieve the build output

      # Step 5: Disable Jekyll for GitHub Pages
      - name: Disable Jekyll
        run: echo > ./dist/.nojekyll

      # Step 6: Upload the static files for deployment
      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          path: ./dist
